struct SampleInfo {
	octet state; // Combines SampleState, InstanceState, ViewState
	unsigned long long sequence_number;
	unsigned long session_time_offset; // milliseconds up to 53 days
};
struct SampleInfoDelta {
	octet state; // Combines SampleState, InstanceState, ViewState
	octet info_seq_number_delta;
	unsigned short info_timestamp_delta; // milliseconds
};

struct SampleData {
	sequence&lt; octet&gt; serialized_data;
};
typedef sequence&lt; SampleData&gt; SampleDataSeq;

struct Sample {
	SampleInfo info;
	SampleData data;
};
typedef sequence&lt; Sample&gt; SampleSeq;

struct SampleDelta {
	SampleInfoDelta info_delta;
	SampleData data;
};

struct SamplePacked {
	SampleInfo info_base;
	sequence&lt; SampleDelta&gt; sample;
};
typedef sequence&lt; SamplePacked&gt; SamplePackedSeq;

union RT_Data switch (octet) {
case 1: // Used to read data with no sample info
	SampleDataSeq data_seq;
case 2: // Used to read data with no info
	SampleSeq sample_seq;
case 3: // Used to read data with compact sample info
	SamplePackedSeq sample_packed_seq;
};